services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - ai_model
    networks:
      - app-network

  ai_model:
    build:
      context: ./ai_model
    ports:
      - "8001:8001"
    environment:
      - GIT_PYTHON_REFRESH=quiet   
    networks:
      - app-network
  mlflow:
    build:
      context: ./mlflow
    ports:
      - "5005:5005"
    networks:
      - app-network
    volumes:
      - ./mlflow:/mlflow   
networks:
  app-network:
    driver: bridge
